# Generated by Django 5.2.2 on 2025-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=13)),
                ('edition', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('cote', models.CharField(max_length=10)),
                ('collection', models.CharField(max_length=200)),
                ('read_level', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=2000)),
                ('language', models.CharField(max_length=200)),
                ('borrow_date', models.CharField(max_length=200)),
                ('return_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
