# Generated by Django 5.2.2 on 2025-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0002_genre_remove_book_borrow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
