# Generated by Django 5.2.2 on 2025-09-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0003_book_copy_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='lighthouse.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='lighthouse.genre'),
        ),
    ]
