# Generated by Django 5.2.2 on 2026-03-24 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0005_alter_book_author_alter_book_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
