# Generated by Django 5.2.16 on 2026-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lighthouse", "0006_alter_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
