# Generated by Django 5.2.16 on 2026-07-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lighthouse", "0007_book_cover_alter_book_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="livres", to="lighthouse.category"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
