# Generated by Django 5.2.16 on 2026-07-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lighthouse", "0008_alter_category_options_alter_book_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
